"""Added a new column summary

Revision ID: 7456e0a3f9e1
Revises: e6cf75354a74
Create Date: 2024-05-31 11:27:41.871750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7456e0a3f9e1'
down_revision: Union[str, None] = 'e6cf75354a74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('summary', sa.String(), nullable=True))
    op.alter_column('posts', 'date',
               existing_type=sa.DATETIME(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'date',
               existing_type=sa.String(),
               type_=sa.DATETIME(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.drop_column('posts', 'summary')
    # ### end Alembic commands ###
